# -*- coding: utf-8 -*-
"""ASSIGNMENT-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uss2Ep4-vxHNFMm8p6_lMYqa87Lpxunh

## Exercises

Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

** What is 7 to the power of 4?**
"""

print(7**4)

"""** Split this string:**

    s = "Hi there Sam!"
    
**into a list. **
"""

s="Hi there Sam!"
print(s.split())

"""** Given the variables:**

    planet = "Earth"
    diameter = 12742

** Use .format() to print the following string: **

    The diameter of Earth is 12742 kilometers.
"""

planet="Earth"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet,diameter))



"""** Given this nested list, use indexing to grab the word "hello" **"""

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

lst=[1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
print(lst[3][1][2][0])

"""** Given this nest dictionary grab the word "hello". Be prepared, this will be annoying/tricky **"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

"""** What is the main difference between a tuple and a list? **

---



---


"""

#tuples are immutable,ordered and enclosed within ()
#list are mutable,ordered and enclosed within []
tuple=(1,2,3,4,5)
list=[1,2,3,4,5]
print(type(tuple))
print(type(list))

"""** Create a function that grabs the email website domain from a string in the form: **

    user@domain.com
    
**So for example, passing "user@domain.com" would return: domain.com**
"""

def domainGet(email):
  print( " " +email.split('@')[-1])
email=input('Enter your email id')
domainGet(email)



"""** Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization. **"""

def countWord(string):
  if 'dog' in string.lower():
    print('True')
  else:
    print('False')
string=input('Enter a string')
countWord(string)



"""** Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **"""

def countdogs(string):
  count=0
  for word in string.lower().split():
     if word=='dog' or  word=='dogs':
       count=count+1
  print(count)  
string=input('Enter a string: ')
countdogs(string)



"""### Problem
**You are driving a little too fast, and a police officer stops you. Write a function
  to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". 
  If your speed is 60 or less, the result is "No Ticket". If speed is between 61 
  and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big    Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all 
  cases. **
"""

def caught_speeding(speed, is_birthday):
    
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'

def speeding(speed, birthday):
    print('Enter your speed and birthday: ')
    if birthday == '30/03/2002':
        speed = speed - 5
    else:
        speed = speed
    if speed<= 60:
        print("You pass.")
    elif speed > 61 and s <= 80:
        print("You get a small ticket")
    else:
        print("You get a big ticket.")
a=input('enter your speed and birthday: ' )
speeding(speed, birthday)



"""Create an employee list with basic salary values(at least 5 values for 5 employees)  and using a for loop retreive each employee salary and calculate total salary expenditure. """

class Employee:
        count=0
        def __init__(self, name, desig, salary):
            self.name=name
            self.desig=desig
            self.salary=salary
            Employee.count+=1
        def displayCount(self):
            print("There are %d employees" % Employee.count)
        def displayDetails(self):
            print("Name:", self.name, ", Designation:", self.desig, ", Salary:", self.salary)
e1=Employee("John", "Manager", 80000)
e2=Employee("Mike", "Team Leader", 50000)
e3=Employee("Derek", "Programmer", 30000)
e4=Employee("Raj", "Assistant", 25000)
e4.displayCount()
print("Details of all employee:")
e1.displayDetails()
e2.displayDetails()
e3.displayDetails()
e4.displayDetails()

"""Create two dictionaries in Python:

First one to contain fields as Empid,  Empname,  Basicpay

Second dictionary to contain fields as DeptName,  DeptId.

Combine both dictionaries. 
"""

dict1={'Empid': 1,'Empname': 'Ramya','Basicpay': 20000}
dict2={'DeptName':'IT','DeptId':125}
dict3= merge (dict1, dict2)
print(dict3)

